# We want to create a new Release whenever we Tag a given commit/build.
# Typically this will be for a given CI build that we've tested as working.
#
# Expected workflow is to test a manual build, and if it's
# working, tag it for release. This yml will auto-build and release that Tag.

name: Release upon Tag

# Watch for Tags and run when we see a new one pushed.
# The release branch must be the default branch for this to trigger.

on:
  # Automatic on new Tag
  push:
    tags:
      - '*'
  # manual builds
  workflow_dispatch:
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Create a Release build for SR-lib'
        # Default value if no value is explicitly provided
        default: 'World'
        # Input has to be provided for the workflow to run
        required: true

jobs:
  tagged_release:
    name: Create Release
    runs-on: windows-2022

    permissions:
      contents: write
      actions: read

    steps:
      - name: Checkout master
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
        
      - name: Show all Visual Studio installs
        shell: cmd
        run: |
          "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -all
          echo(
          echo === Installed VS ===
          dir "C:\Program Files (x86)\Microsoft Visual Studio"
          dir "C:\Program Files\Microsoft Visual Studio"
          echo(
          echo === Installed toolsets ===
          dir "C:\Program Files (x86)\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC"
          dir "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC"
          
      - name: Install v141 toolset
        shell: cmd
        run: |
          "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installer.exe" modify \
            --installPath "C:\Program Files\Microsoft Visual Studio\2022\Enterprise" \
            --add Microsoft.VisualStudio.Component.VC.v141.x86.x64 \
            --installWhileDownloading \
            --quiet
    
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Install 7-Zip
        shell: cmd
        run: |
          choco install 7zip -y

# Build via Publish.bat, but tell the script to skip version bump.

      - name: Build into Zip Release
        shell: cmd
        run: |
          echo(
          echo === Building Win32 target ===
          MSBUILD StereoVisionHacks.sln /p:Configuration="Debug" /p:Platform=Win32 /v:minimal /target:rebuild /p:PlatformToolset=v141
          MSBUILD StereoVisionHacks.sln /p:Configuration="Release" /p:Platform=Win32 /v:minimal /target:rebuild /p:PlatformToolset=v141
          echo(
          echo === Building x64 target ===
          MSBUILD StereoVisionHacks.sln /p:Configuration="Debug" /p:Platform=x64 /v:minimal /target:rebuild /p:PlatformToolset=v141
          MSBUILD StereoVisionHacks.sln /p:Configuration="Release" /p:Platform=x64 /v:minimal /target:rebuild /p:PlatformToolset=v141
          
      - name: Get tag name
        shell: bash
        run: |
          echo "TAG_NUM=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Compress release to .7z
        shell: bash
        run: |
          cd "SR-lib"
          7z a -t7z "SR-lib_v${TAG_NUM}.7z" "./*"
      
      - name: List contents of .7z file for log info
        shell: bash
        run: |
          7z l "SR-lib/SR-lib_v${TAG_NUM}.7z"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NUM }}
          name: Release build for v${{ env.TAG_NUM }} (x32, x64)
          files: "SR-lib/SR-lib_v${{ env.TAG_NUM }}.7z"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
